<?php
require_once __DIR__.'/../../includes/runtime.php';
require_once __DIR__.'/../../includes/helpers.php';
require_once __DIR__.'/../../includes/service_client.php';
require_login();
$svc=service('health');
if($_SERVER['REQUEST_METHOD']==='POST'){
    try { $message=$svc->handle((string)($_POST['action']??''),$_POST,current_user()); flash('success',$message); }
    catch(Throwable $e){ flash('error','Unable to save record: '.$e->getMessage()); }
    redirect('/modules/health_safety/index.php?released=1&release_status=success');
}
$filterDate=(string)($_GET['date']??'');
$showAllHealth=isset($_GET['health_all']) && $_GET['health_all']==='1';
$showAllIncidents=isset($_GET['incident_all']) && $_GET['incident_all']==='1';
$showAllRequests=isset($_GET['request_all']) && $_GET['request_all']==='1';
$incidents=$svc->incidents($filterDate); $health=$svc->healthRecords($filterDate);
$fileRequests=$svc->fileRequests($filterDate,null);
$pendingAll=array_values(array_filter($fileRequests,fn($f)=>$f['action_type']==='Requested'));
$pending=$showAllRequests?$pendingAll:array_slice($pendingAll,0,5);
$releaseEmployee=(string)($_GET['release_requester']??'');
page_header('Health, Safety & Welfare','health'); show_flash(); ?>
<div class="gw-breadcrumb"><span>Great Solomon Manpower Services Inc.</span><span>/</span><strong>Health, Safety &amp; Welfare</strong></div>
<section class="gw-hero"><div><div class="eyebrow">MODULE 1</div><h1>Health, Safety &amp; Welfare</h1><p>Review health records, safety incidents, welfare requests and released files.</p></div></section>
<section class="gw-quick-actions"><a href="#pending-requests">Pending Request Files</a><a href="#file-release">Release File</a></section>
<section class="gw-stats"><div class="gw-stat"><span class="gw-stat-label">Incidents</span><div class="gw-stat-value"><?=count($incidents)?></div><div class="gw-stat-meta">Recorded</div></div><div class="gw-stat"><span class="gw-stat-label">Health Records</span><div class="gw-stat-value"><?=count($health)?></div><div class="gw-stat-meta">Recorded</div></div></section>
<section class="record-form" id="pending-requests"><div class="gw-panel-head"><div><h2>Pending Request Files</h2><span><?= $showAllRequests ? 'Showing all matching requests' : 'Showing the latest 5 requests' ?><?= $filterDate ? ' for '.e($filterDate) : '' ?></span></div><span class="material-symbols-outlined">manage_search</span></div>
<form method="get" class="dashboard-date-filter" style="padding:0 18px 14px;justify-content:flex-end"><span class="dashboard-date-filter-label"><span class="material-symbols-outlined">filter_alt</span>Request date</span><div class="dashboard-date-input-wrap"><input type="date" name="date" value="<?=e($filterDate)?>"></div><button class="gw-btn secondary"><span class="material-symbols-outlined">filter_alt</span>Filter</button><?php if($filterDate):?><a class="gw-btn secondary" href="<?=e(url('/modules/health_safety/index.php'))?>#pending-requests">Clear</a><?php endif;?><?php if($showAllRequests):?><a class="gw-btn secondary" href="<?=e(url('/modules/health_safety/index.php'.($filterDate?'?date='.rawurlencode($filterDate):'')))?>#pending-requests">Show latest 5</a><?php else:?><a class="gw-btn primary" href="<?=e(url('/modules/health_safety/index.php?request_all=1'.($filterDate?'&date='.rawurlencode($filterDate):'')))?>#pending-requests">See all pending requests</a><?php endif;?></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Requester</th><th>Requested File</th><th>Type</th><th>Request Date</th><th>Notes</th><th>Action</th></tr></thead><tbody><?php foreach($pending as $f):?><tr><td><?=e($f['employee_name'])?></td><td><?=e($f['file_name'])?></td><td><?=e($f['file_type'])?></td><td><?=e($f['request_date'])?></td><td><?=e($f['notes'])?></td><td><a class="gw-btn primary" href="?release_requester=<?=urlencode($f['employee_name'])?>#file-release">Process &amp; Release</a></td></tr><?php endforeach;?><?php if(!$pending):?><tr><td colspan="6" class="empty">No pending file requests.</td></tr><?php endif;?></tbody></table></div></section>
<section class="record-form" id="file-release"><div class="gw-panel-head"><h2>Release File</h2><span>Choose a stored data/file and send it to the requester.</span></div><form id="releaseFileForm" method="post"><input type="hidden" name="action" value="release_file"><div id="releaseStorageFileIds"></div><div class="form-grid"><div><label>Requester</label><input name="employee_name" required value="<?=e($releaseEmployee)?>" readonly></div><div class="full"><label>Add File</label><button type="button" class="gw-btn secondary" onclick="showReleaseFileStoragePicker()"><span class="material-symbols-outlined">folder_open</span> Add File</button><div id="selectedReleaseFile" class="selected-files-list"><div class="selected-file-note">No data/file selected.</div></div></div><div><label>Release Date</label><input type="date" name="file_date" required value="<?=date('Y-m-d')?>"></div><div class="full"><label>Notes</label><textarea name="file_notes" placeholder="Optional release note..."></textarea></div></div><div class="record-actions"><button type="submit" class="gw-btn primary">Release File</button></div></form></section>
<section class="gw-panel" style="margin-top:20px"><div class="gw-panel-head"><h2>File Request &amp; Release History</h2><span><?=count($fileRequests)?> records</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Requester</th><th>File</th><th>Type</th><th>Action</th><th>Date</th><th>Notes</th></tr></thead><tbody><?php foreach($fileRequests as $f):?><tr><td><?=e($f['employee_name'])?></td><td><?=e($f['file_name'])?></td><td><?=e($f['file_type'])?></td><td><?=e($f['action_type'])?></td><td><?=e($f['request_date'])?></td><td><?=e($f['notes'])?></td></tr><?php endforeach;if(!$fileRequests):?><tr><td colspan="6" class="empty">No file requests or releases recorded.</td></tr><?php endif;?></tbody></table></div></section>
<section class="gw-panel" style="margin-top:20px"><div class="gw-panel-head"><div><h2>Health Records</h2><span><?= $showAllHealth ? 'Showing all matching records' : 'Showing the latest 5 records' ?><?= $filterDate ? ' for '.e($filterDate) : '' ?></span></div><span class="material-symbols-outlined">manage_search</span></div><form method="get" class="date-filter" style="padding:0 18px 14px;justify-content:flex-end"><span class="dashboard-date-filter-label"><span class="material-symbols-outlined">filter_alt</span>Record date</span><input type="date" name="date" value="<?=e($filterDate)?>"><button class="gw-btn secondary">Filter</button><?php if($filterDate):?><a class="gw-btn secondary" href="<?=e(url('/modules/health_safety/index.php'))?>#health-records">Clear</a><?php endif;?><?php if($showAllHealth):?><a class="gw-btn secondary" href="<?=e(url('/modules/health_safety/index.php'.($filterDate?'?date='.rawurlencode($filterDate):'')))?>#health-records">Show latest 5</a><?php else:?><a class="gw-btn primary" href="<?=e(url('/modules/health_safety/index.php?health_all=1'.($filterDate?'&date='.rawurlencode($filterDate):'')))?>#health-records">See all health records</a><?php endif;?></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Employee</th><th>Checkup Date</th><th>Record Type</th><th>Fitness Status</th><th>Notes</th></tr></thead><tbody><?php $healthView=$showAllHealth?$svc->healthRecords($filterDate):array_slice($health,0,5); foreach($healthView as $r):?><tr><td><?=e($r['employee_name'])?></td><td><?=e($r['checkup_date'])?></td><td><?=e($r['record_type'])?></td><td><?=e($r['fitness_status'])?></td><td><?=e($r['notes'])?></td></tr><?php endforeach;if(!$healthView):?><tr><td colspan="5" class="empty">No health records for the selected filter.</td></tr><?php endif;?></tbody></table></div></section>
<section class="gw-panel" style="margin-top:20px"><div class="gw-panel-head"><div><h2>Safety Incident Reports</h2><span><?= $showAllIncidents ? 'Showing all matching records' : 'Showing the latest 5 records' ?><?= $filterDate ? ' for '.e($filterDate) : '' ?></span></div><span class="material-symbols-outlined">manage_search</span></div><form method="get" class="date-filter" style="padding:0 18px 14px;justify-content:flex-end"><span class="dashboard-date-filter-label"><span class="material-symbols-outlined">filter_alt</span>Incident date</span><input type="date" name="date" value="<?=e($filterDate)?>"><button class="gw-btn secondary">Filter</button><?php if($filterDate):?><a class="gw-btn secondary" href="<?=e(url('/modules/health_safety/index.php'))?>#incident-reports">Clear</a><?php endif;?><?php if($showAllIncidents):?><a class="gw-btn secondary" href="<?=e(url('/modules/health_safety/index.php'.($filterDate?'?date='.rawurlencode($filterDate):'')))?>#incident-reports">Show latest 5</a><?php else:?><a class="gw-btn primary" href="<?=e(url('/modules/health_safety/index.php?incident_all=1'.($filterDate?'&date='.rawurlencode($filterDate):'')))?>#incident-reports">See all safety incident reports</a><?php endif;?></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Title</th><th>Employee</th><th>Date</th><th>Severity</th><th>Status</th></tr></thead><tbody><?php $incidentView=$showAllIncidents?$incidents:array_slice($incidents,0,5); foreach($incidentView as $r):?><tr><td><?=e($r['title'])?></td><td><?=e($r['employee_name'])?></td><td><?=e($r['incident_date'])?></td><td><?=e($r['severity'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach;if(!$incidentView):?><tr><td colspan="5" class="empty">No safety incident reports for the selected filter.</td></tr><?php endif;?></tbody></table></div></section>
<script>
document.getElementById('releaseFileForm')?.addEventListener('submit',function(e){if(!document.querySelector('input[name="storage_file_ids[]"]')){e.preventDefault();showModal('Add File','Please choose at least one data/file from Data Storage first.');return;}if(!window.confirm('are you sure you want to release this file ? ')){e.preventDefault();}});
<?php if(isset($_GET['released']) && $_GET['released']==='1' && ($_GET['release_status']??'')==='success'): ?>showModal('successfully sent !','The selected file was successfully sent to the requester.');<?php endif; ?>
</script>
<?php page_footer(); ?>
