<?php
require_once __DIR__.'/../../includes/helpers.php';
require_once __DIR__.'/../../includes/service_client.php';
require_login();
$svc=service('legal');
if($_SERVER['REQUEST_METHOD']==='POST'){
    try { $message=$svc->handle((string)($_POST['action']??''),$_POST,current_user()); flash('success',$message); }
    catch(Throwable $e){ flash('error','Unable to save record: '.$e->getMessage()); }
    redirect('/modules/legal_compliance/index.php');
}
$u=current_user();
$reportDate=(string)($_GET['report_date']??'');
$showAllReports=isset($_GET['report_all']) && $_GET['report_all']==='1';
$obs=$svc->complianceReports($reportDate,$showAllReports?null:5);
$auditDate=(string)($_GET['audit_date']??'');
$showAllAudit=isset($_GET['audit_all']) && $_GET['audit_all']==='1';
$staffAdminAudit=(($u['role']??'')==='Administrator') ? service('audit')->latestStaffAdmin($auditDate, $showAllAudit ? null : 5) : [];
page_header('Legal & Compliance','legal');show_flash(); ?>
<div class="gw-breadcrumb"><span>Great Solomon Manpower Services Inc.</span><span>/</span><strong>Legal &amp; Compliance</strong></div>
<section class="gw-hero"><div><div class="eyebrow">MODULE 2</div><h1>Legal &amp; Compliance</h1><p>Record and review compliance reports.</p></div></section>
<section class="gw-quick-actions"><a href="#compliance-report"><span class="material-symbols-outlined">description</span> Add Compliance Report</a><a href="#compliance-reports"><span class="material-symbols-outlined">list_alt</span> Compliance Reports</a></section>
<section class="gw-stats"><div class="gw-stat"><span class="gw-stat-label">Compliance Reports</span><div class="gw-stat-value"><?=count($obs)?></div><div class="gw-stat-meta">Showing <?= $showAllReports ? 'all matching' : 'latest 5' ?> reports</div></div></section>
<section class="record-form" id="compliance-report"><div class="gw-panel-head"><h2>Add Compliance Report</h2><span>Database-backed</span></div><form method="post"><input type="hidden" name="action" value="add_report"><div class="form-grid"><div><label>Name</label><input name="report_name" required></div><div><label>Role</label><input name="report_role" required></div><div><label>Contact No.</label><input name="contact_no" required></div><div class="full"><label>Compliance</label><textarea name="compliance_note" required placeholder="Write the compliance concern/complaint like a note..."></textarea></div></div><div class="record-actions"><button class="gw-btn primary">Save Compliance Report</button></div></form></section>
<section class="gw-panel" id="compliance-reports"><div class="gw-panel-head"><div><h2>Compliance Reports</h2><span><?= $showAllReports ? 'Showing all matching reports' : 'Showing the latest 5 reports' ?><?= $reportDate ? ' for '.e($reportDate) : '' ?></span></div><span class="material-symbols-outlined">manage_search</span></div>
<form method="get" class="date-filter" style="padding:0 18px 14px;justify-content:flex-end"><span class="dashboard-date-filter-label"><span class="material-symbols-outlined">filter_alt</span>Report date</span><input type="date" name="report_date" value="<?=e($reportDate)?>"><button class="gw-btn secondary" type="submit">Filter</button><?php if($reportDate):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'))?>#compliance-reports">Clear</a><?php endif;?><?php if($showAllReports):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'.($reportDate?'?report_date='.rawurlencode($reportDate):'')))?>#compliance-reports">Show latest 5</a><?php else:?><a class="gw-btn primary" href="<?=e(url('/modules/legal_compliance/index.php?report_all=1'.($reportDate?'&report_date='.rawurlencode($reportDate):'')))?>#compliance-reports">See all compliance reports</a><?php endif;?></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Role</th><th>Contact No.</th><th>Date &amp; Time</th><th>Compliance</th><th></th></tr></thead><tbody><?php foreach($obs as $r):?><tr><td><?=e($r['report_name']??$r['title'])?></td><td><?=e($r['report_role']??$r['owner'])?></td><td><?=e($r['contact_no']??'')?></td><td><?=e($r['reported_at']??$r['created_at'])?></td><td><?=nl2br(e($r['compliance_note']??''))?></td><td><form method="post" onsubmit="return confirm('Delete this compliance report?')"><input type="hidden" name="action" value="delete_report"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="gw-btn btn-danger">Delete</button></form></td></tr><?php endforeach;if(!$obs):?><tr><td colspan="6" class="empty">No compliance reports recorded.</td></tr><?php endif;?></tbody></table></div></section>
<?php if (($u['role'] ?? '') === 'Administrator'): ?>
<section class="gw-panel" id="staff-admin-audit-trail" style="margin-top:20px"><div class="gw-panel-head"><div><h2>Staff &amp; Admin Audit Trail</h2><span><?= $showAllAudit ? 'Showing all matching audit records' : 'Showing the latest 5 audit records' ?><?= $auditDate ? ' for '.e($auditDate) : '' ?></span></div><span class="material-symbols-outlined">manage_search</span></div>
<form method="get" class="date-filter" style="padding:0 18px 14px;justify-content:flex-end"><span class="dashboard-date-filter-label"><span class="material-symbols-outlined">filter_alt</span>Audit date</span><input type="date" name="audit_date" value="<?=e($auditDate)?>"><button class="gw-btn secondary">Filter</button><?php if($auditDate):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'))?>#staff-admin-audit-trail">Clear</a><?php endif;?><?php if($showAllAudit):?><a class="gw-btn secondary" href="<?=e(url('/modules/legal_compliance/index.php'.($auditDate?'?audit_date='.rawurlencode($auditDate):'')))?>#staff-admin-audit-trail">Show latest 5</a><?php else:?><a class="gw-btn primary" href="<?=e(url('/modules/legal_compliance/index.php?audit_all=1'.($auditDate?'&audit_date='.rawurlencode($auditDate):'')))?>#staff-admin-audit-trail">See all audit trails</a><?php endif;?></form>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Gmail</th><th>Role</th><th>Module</th><th>Action</th><th>Details</th><th>Date &amp; Time</th></tr></thead><tbody><?php foreach($staffAdminAudit as $a): ?><tr><td><?=e($a['name'])?></td><td><?=e($a['email'])?></td><td><?=e($a['role'])?></td><td><?=e($a['module'])?></td><td><?=e($a['action'])?></td><td><?=e($a['details'])?></td><td><?=e($a['created_at'])?></td></tr><?php endforeach; ?><?php if(!$staffAdminAudit): ?><tr><td colspan="7" class="empty">No staff or administrator audit records match the selected filter.</td></tr><?php endif; ?></tbody></table></div></section>
<?php endif; ?>
<?php page_footer(); ?>
